accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home')
]

auth_login/urls.py
from django.urls import path, include
from auth_login import views
from django.contrib.auth import views as auth_views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    #path('profile/purchases/<int:id>', views.purchases, name='purchases'),
    path('profile/edit', views.editProfile, name='edit'),
    path('profile/change_password', views.change_password, name='change_password'),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('auth/', include('auth_login.urls', namespace='auth')),
    #Me trae las funciones de reseteo de contraseña que provee Django
    path('accounts/', include('django.contrib.auth.urls')), 
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

GENDERS = (
    ('H', 'Hombre'),
    ('M', 'Mujer'),
    ('O', 'Otro'),
)
# Create your models here.
class Tabla_test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    columna_uno = models.CharField(max_length=200)
    columna_dos = models.CharField(max_length=200)
    columna_tres = models.CharField(max_length=200)
    columna_cuatro = models.CharField(max_length=200)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, default='No indica')
    gender = models.CharField(max_length=1, choices=GENDERS, default='N')
    city = models.CharField(max_length=50, default='No indica')
    phone = models.IntegerField(default=0)
    
    def __str__(self):
        return self.user.first_name

# Función que se ejecuta cuando se crea un usuario nuevo, realiza un trigger que asocia ese usuario nuevo a un perfil UserProfile
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

auth_login/models.py
from django.db import models

# Create your models here.

auth_login/forms.py
from django import forms
from auth_login import views
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='email', required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'           
        ]
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = (self.cleaned_data["first_name"])
        user.last_name = (self.cleaned_data["last_name"])
        user.email = (self.cleaned_data["email"])

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

accounts/views.py
from django.shortcuts import render, HttpResponse
from accounts.models import Tabla_test
# Create your views here.

def home(request):
    numbers = [1,2,3,4,5]
    name = 'Cris'

    data = {}
    data['myName'] = name
    data['numbers'] = numbers
    #data['testItem'] = Tabla_test.objects.get(pk=1)

    return render(request, 'home.html', data)

auth_login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from auth_login.forms import RegistrationForm, EditProfileForm
from django.db import IntegrityError
from datetime import datetime
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

def register(request):
    template_name = 'register.html'
    #data['form'] = RegistrationForm(request.POST or None)

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            auth.logout(request)
            #auth.login(request, user)
            return redirect('auth:login') 
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request, template_name, args)

def login(request):
    template_name = 'login.html'
    data = {}

    auth.logout(request)
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(
            username=username,
            password=password
        )

        if user is not None:
            ## Usuario autenticado
            if user.is_active:
                #Usuario valido
                auth.login(request, user)
                return redirect('auth:profile')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Error user not active.'
                )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Usuario o Contraseña incorrectos.'
            )
    else:
        return render(request, template_name, data)

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        return redirect('accounts:home')
    else:
        print('no logeado')
        return redirect('accounts:home')


def profile(request):
    template_name = 'profile.html'
    
    data = {'user': UserProfile.objects.get(user=request.user.id)}
    return render(request, template_name, data)



def editProfile(request):
    data = {}
    template_name = 'edit_profile.html'

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('auth:profile')
    else:
        form = EditProfileForm(instance=request.user)
        data = {'form': form}
        return render(request, template_name, data) 

    return render(request, template_name, data)

def change_password(request):
    data = {}
    template_name = 'change_password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('auth:profile')
        else:
            return redirect('auth:change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        data = {'form': form}
        return render(request, template_name, data)

#def purchases(request, id):
# data = {}
# template_name = 'purchases.html'
# 
# data['compras'] = Detail.objects.filter(Numero_boleta=id)
# data['total'] = Sale.objects.get(pk=id)
#   return render(request, template_name, data)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'accounts/style.css'%}" type="text/css">
  <!--Bootstrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <!--Bootstrap-->
  <script src="https://kit.fontawesome.com/686111fdd6.js" crossorigin="anonymous"></script>
  <title>{% block head %}{% endblock %}</title>
</head>

<body>
  {% if request.user.is_authenticated %}
  <div class="container-{breakpoint}">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style="padding-left: 30px;">
      <a class="navbar-brand" href="{% url 'accounts:home' %}">Login System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
          </li>
          <li class="nav-item mr-auto">
            <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
          </li>
          <!-- Menu desplegable -->
          <!--           
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> 
          -->
          <!-- Menu desplegable -->
        </ul>
      </div>
    </nav>
  </div>
  {% else %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-left: 30px;">
    <a class="navbar-brand" href="#">Login System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
        </li>
      </ul>
    </div>
  </nav>
  {% endif %}
  <div class="container h-100">
    {% block body %}

    {% endblock %}
  </div>
</body>

</html>

accounts/templates/home.html
{% extends 'base.html' %}
{% block head %}
Home
{% endblock %}
{% block body %}

{% endblock %}

auth_login/templates/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body %}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5 h-100">
    <div class="col-md-6 mx-auto my-auto">
        <h2>Cambiar Contraseña</h2>
        <!--Fin titulo-->
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Cambiar contraseña
            </button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock %}

auth_login/templates/edit_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body%}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5">
    <div class="col">
        <h2>Editar perfil</h2>
        <!--Fin titulo-->
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Confirmar cambios
            </button>
            {% endbuttons %}
        </form>

    </div>
</div>
{% endblock %}

auth_login/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
Login Usuario
{% endblock %}
{% block body %}
<div class="row h-100">
    <div class="col-md-6 mx-auto my-auto">
        <form class="form-signin" method="POST">
            {% csrf_token %}
            <div class="text-center mb-4">
                <h1>User login</h1>
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="form-label-group w-50 mx-auto mb-3">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="Username" required
                    autofocus>
            </div>

            <div class="form-label-group w-50 mx-auto mb-3">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                    required>
            </div>

            <div class="checkbox mb-3 w-50 mx-auto mb-1">
                <label>
                    <input type="checkbox" value="remember-me"> Recuérdame
                </label>
            </div>
            <div class="mb-3 w-50 mx-auto">
                <p><button class="btn btn-lg btn-block     btn-primary" type="submit">Entrar</button> <span><a href="{% url 'auth:register' %}">Registrarse</a></span><span><a href="/accounts/password_reset/">¿Olvidó su contraseña?</a></span></p>
            </div>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2019</p>
        </form>
    </div>
</div>
{% endblock %}

<!--<div class="col-12 col-sm-6 mt-5">
        <div class="jumbotron">
            <h1 class="mb-5">CREAR UNA CUENTA</h1>
            <p class="lead">Crear una cuenta es fácil. Ingresa tu dirección de correo electrónico, llena el formulario
                de la página siguiente y disfruta de tus beneficios</p>
            <hr class="">
            <a class="btn btn-primary btn-lg mt-3" href="{% url 'auth:register' %}" role="button">Registrarse</a>
        </div>
    </div>-->

auth_login/templates/password_reset_form.html
{% extends 'base.html' %}

{% block head %}Forgot Your Password?{% endblock %}

{% block body %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

auth_login/templates/profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body %}
<!--Formulario-->

<div class="row h-100">
  <div class="col-md-6 mx-auto my-auto">
    <div class="card mb-5 align-center">
      <div class="card-body">
        <h3 class="card-title"><strong>Tus datos</strong></h3>
        <h6>Nombre</h6>
        <p class="card-text">{{user.user.first_name}} {{user.user.last_name}}</p>
        <h6>Email</h6>
        <p class="card-text">{{user.user.email}}</p>
        <h6>Calle</h6>
        <p class="card-text">{{user.address}}</p>
        <h6>Ciudad</h6>
        <p class="card-text">{{user.city}}</p>
        <h6>Telefono</h6>
        <p class="card-text">{{user.phone}}</p>
        <a href="{% url 'auth:edit' %}" class="btn btn-primary mr-2"><i class="far fa-edit text-center"></i></a>
        <a href="{% url 'auth:change_password' %}" class="btn btn-primary"><i class="fas fa-key"></i></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}


<!-- <div class="row round-borderform">
     <div class="col">
        <h2>Perfil</h2>  -->

auth_login/templates/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Crear usuario
{% endblock %}
{% block body %}
<!--Titulo-->
<div class="row round-borderform">
    <div class="col-md-12">
        <h2>Registrarse</h2>
        <!--Fin titulo-->
        
        <!--Formulario-->
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Crear usuario!
            </button>
            {% endbuttons %}
        </form>
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}